<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHvlOhDG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHvlOhDG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHvlOhDG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHvlOhDG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHvlOhDG\App_KernelDevDebugContainer([
    'container.build_hash' => 'HvlOhDG',
    'container.build_id' => '6486aaa8',
    'container.build_time' => 1698466417,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHvlOhDG');
