<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDfxRVXI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDfxRVXI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDfxRVXI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDfxRVXI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDfxRVXI\App_KernelDevDebugContainer([
    'container.build_hash' => 'DfxRVXI',
    'container.build_id' => 'a37888ab',
    'container.build_time' => 1701557031,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDfxRVXI');
