<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDRGNele\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDRGNele/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDRGNele.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDRGNele\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDRGNele\App_KernelDevDebugContainer([
    'container.build_hash' => 'DRGNele',
    'container.build_id' => 'bb7a4afd',
    'container.build_time' => 1712541101,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDRGNele');
