<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAskgfTQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAskgfTQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAskgfTQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAskgfTQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAskgfTQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'AskgfTQ',
    'container.build_id' => '42ef2749',
    'container.build_time' => 1710716383,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAskgfTQ');
